from .appointment import Appointment
from .doctor import Doctor
from .hospital import Hospital
from .department import Department
from .staff import Staff
from .shift import Shift
from .hospitalfeedback import HospitalFeedback
from .patient import Patient
from .review import Review
from .dayweek import DayOfWeek
from .disease import Disease
from .language import Language
from .facility import Facility
from .treatment import Treatment
from .city import City