# Generated by Django 5.1.5 on 2025-01-30 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Health', '0002_remove_patient_insurance_policy_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_associated', to='Health.doctor'),
        ),
    ]
