# Generated by Django 5.1.5 on 2025-01-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Health', '0003_staff_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='location',
        ),
        migrations.AddField(
            model_name='appointment',
            name='location_type',
            field=models.CharField(choices=[('Hospital', 'Hospital'), ('Clinic', 'Clinic')], default='Hospital', max_length=10),
        ),
    ]
