# Generated by Django 5.1.5 on 2025-01-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Health', '0004_remove_appointment_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='address',
            field=models.CharField(blank=True, help_text='Clinic or personal address', max_length=500, null=True),
        ),
    ]
