# Generated by Django 5.1.5 on 2025-01-31 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Health', '0006_treatment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospital',
            options={},
        ),
        migrations.AddField(
            model_name='hospital',
            name='hospital_type',
            field=models.CharField(choices=[('hospital', 'Hospital'), ('clinic', 'Clinic')], default='hospital', max_length=10),
        ),
        migrations.AddField(
            model_name='hospital',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
