# Generated by Django 5.1.5 on 2025-02-02 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Health', '0009_alter_hospital_city_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='password',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Canceled', 'Canceled'), ('Rescheduled', 'Rescheduled'), ('No-Show', 'No-Show')], db_index=True, default='Scheduled', max_length=15),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='treatment_type',
            field=models.CharField(choices=[('ayurveda', 'Ayurveda'), ('homeopathy', 'Homeopathy'), ('allopathy', 'Allopathy')], max_length=20),
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='head_of_department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='treatment_type',
            field=models.CharField(choices=[('ayurveda', 'Ayurveda'), ('homeopathy', 'Homeopathy'), ('allopathy', 'Allopathy')], max_length=20),
        ),
        migrations.AlterField(
            model_name='hospitalfeedback',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='Health.hospital'),
        ),
        migrations.AlterField(
            model_name='hospitalfeedback',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_feedbacks', to='Health.patient'),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('doctor', 'patient', 'appointment_date')},
        ),
    ]
