# Generated by Django 5.1.5 on 2025-02-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Health', '0010_alter_doctor_options_remove_doctor_password_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={},
        ),
        migrations.AddField(
            model_name='doctor',
            name='password',
            field=models.CharField(default='default_password', max_length=128),
        ),
    ]
