# Generated by Django 5.1.5 on 2025-02-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Health', '0011_alter_doctor_options_doctor_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
