# Generated by Django 5.1.5 on 2025-02-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Health', '0012_alter_doctor_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
