# Generated by Django 5.1.5 on 2025-02-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Health', '0013_review_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
