# Generated by Django 5.1.5 on 2025-02-06 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Health', '0015_disease'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='category',
        ),
    ]
