# Generated by Django 5.1.5 on 2025-02-07 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Health', '0016_remove_disease_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiseaseCategory',
        ),
    ]
