# Generated by Django 5.1.5 on 2025-02-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Health', '0017_delete_diseasecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='original_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Canceled', 'Canceled'), ('Rescheduled', 'Rescheduled'), ('No-Show', 'No-Show')], db_index=True, default='Scheduled', max_length=15),
        ),
    ]
