# Generated by Django 5.1.5 on 2025-02-18 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Health', '0018_appointment_original_date_alter_appointment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='original_date',
        ),
    ]
