# Generated by Django 5.1.5 on 2025-02-19 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Health', '0019_remove_appointment_original_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Health.hospital'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('Nurse', 'Nurse'), ('Technician', 'Technician'), ('Administrator', 'Administrator'), ('Lab Assistant', 'Lab Assistant'), ('Security', 'Security'), ('Other', 'Other')], max_length=100),
        ),
    ]
